project:
  type: book
  output-dir: _output
book:
  title: "From Insights to Impact"
  subtitle: "Utility and Failure Modes of Language Models in Clinical Practice"
  author: "Shan Chen"
  back-to-top-navigation: true
  chapters:
    - index.qmd
    - chapters/chap-1.qmd
    - part: "Part I: Potential Utilities of Language Models in Real Clinical Practice"
      chapters:
        - chapters/chap-2.qmd
        - chapters/chap-3.qmd
        - chapters/chap-4.qmd
        - chapters/chap-5.qmd
        - chapters/chap-6.qmd
    - part: "Part II: Potential Failures of Language Models in Medical Settings"
      chapters:
        - chapters/chap-7.qmd
        - chapters/chap-8.qmd
        - chapters/chap-9.qmd
        - chapters/chap-10.qmd
        - chapters/chap-11.qmd
        - chapters/chap-12.qmd
    - chapters/chap-13.qmd
    - chapters/references.qmd
  appendices:
    - chapters/appendix-a.qmd
    - chapters/appendix-b.qmd
    - chapters/appendix-c.qmd
